### ISSUE TITLE
Check if there are any restrictions on IPFS Node in regards to the amount of requests/seconds

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/blockchain-meta#49]
review whether there are any restrictions on IPFS Node in regards to the amount of requests/seconds a single client can make to the node.

Report your findings (any relevant configs) below.

**Comment by nk-the-crazy** [comment]
Done stress test via app.loadimpact.com:

<img width="1367" alt="Screen Shot 2019-03-20 at 11 50 30 AM" src="https://user-images.githubusercontent.com/11713346/54662181-5ab24e80-4b07-11e9-8d07-cf316f3e887b.png">

**Comment by nk-the-crazy** [comment]
Stress test for ipfs.horizontalsystems.xyz (via blazemeter.com)

<img width="1573" alt="Screen Shot 2019-03-20 at 4 59 37 PM" src="https://user-images.githubusercontent.com/11713346/54681532-d5469280-4b36-11e9-86f5-dbafaecaccca.png">

**Comment by uberkerim** [comment]
According to our observation, IPFS performance is not consistent, especially when using ipfs gateway. Sometimes it responds within a second, sometimes it take several minutes to get response. The cause of it is not stress on hardware, but synchronization between ipfs nodes. Thus this issue is out of our control when using ipfs gateways.
